---
swagger: "2.0"
info:
  description: "Test API"
  version: "1.0.1"
  title: "Test API"
# host: "xqagxkd8b7.execute-api.us-east-1.amazonaws.com"
# basePath: "/beta"
schemes:
- "https"
paths:
  /constants:
    get:
      operationId: "getConstants"
      description: "Returns a list of all constants"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
          schema:
            $ref: "#/definitions/ListOfConstants"
        "400":
          description: "400 response"

    
  /calculator:
    post:
      operationId: "requestSum"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "CalculationRequest"
        required: true
        schema:
          $ref: "#/definitions/CalculationRequest"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/AddResponse"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        "400":
          description: "400 response"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:883421610071:function:second/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses: {}
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
        type: "mock"
definitions:
  ListOfConstants:
    type: array
    items: {}
  CalculationRequest:
    type: "object"
    required:
    - "arg1"
    - "arg2"
    properties:
      arg1:
        type: "string"
      arg2:
        type: "string"
  Constant:
    type: "object"
    required: 
    - "name"
    - "value"
    - "system"
    properties:
      name:
        type: string
      value:
        type: number
      system:
        type: boolean
  AddResponse:
    type: "object"
    required:
    - "result"
    - "statusCode"
    - "error"
    properties:
      result:
        type: string
      statusCode:
        type: integer
      error:
        type: string


# Added by API Auto Mocking Plugin
basePath: /heineman/Fall2021Calculator/1.0.1
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com